spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:mariadb://localhost:3306/final_project
    username: root
    password: password
  jpa:
    #show-sql: true
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


connectors:
  order:
    uri: http://localhost:order-service
    mock:
      enabled: true
  warehouse:
    uri: http://localhost:warehouse-service
    mock:
      enabled: true
  mail:
    uri: http://localhost:mail-service
    mock:
      enabled: true
  login:
    uri: http://localhost:login-service
    mock:
      enabled: true


transaction:
  kafka:
    bootstrapServer: ${KAFKA_SERVER:transaction-kafka}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
