version: "3.7"
services:
  catalog:
    image: gabrielefantini/finalprojectwa2_catalog:latest
    networks:
      - "myapp"
    ports: 
     - 8085:8085
  
  eureka:
    image: gabrielefantini/finalprojectwa2_eureka:latest
    networks:
      - "myapp"
  
  mail:
    image: gabrielefantini/finalprojectwa2_mail:latest
    networks:
      - "myapp"
  
  order:
    image: gabrielefantini/finalprojectwa2_order:latest
    networks:
      - "myapp"
  
  wallet:
    image: gabrielefantini/finalprojectwa2_wallet:latest
    networks:
      - "myapp"
  
  warehouse:
    image: gabrielefantini/finalprojectwa2_warehouse:latest
    networks:
      - "myapp"
  
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: final_project
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
    - "myapp"

  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "myapp-zookeeper"
    networks:
      - "myapp"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "myapp-kafka"
    networks:
      - "myapp"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.5.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
    - zookeeper


networks:
  myapp:
    name: "myapp"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          