spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mariadb://localhost:3306/final_project
    username: root
    password: password
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update

connectors:
  wallet:
    uri: http://localhost:wallet-service
    mock: true
  warehouse:
    uri: http://localhost:warehouse-service
    mock: true
  mail:
    uri: http://localhost:mail-service

transaction:
  kafka:
    bootstrapServer: ${KAFKA_SERVER:transaction-kafka}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true