KAFKA_SERVER: localhost:9092
MAIL_URI: localhost:8080
server:
  port: 8082

logging:
  level:
    com.netflix: OFF
    org.apache.kafka.clients.NetworkClient: OFF

transaction:
  debug:
    auto-rollback:
      enabled: false