spring:
  application:
    name: mail-service
  mail:
    host: smtp.ethereal.email
    protocol: smtp
    port: 587
    username: angel.collins50@ethereal.email
    password: jTdeaSXZbBUeA78ubs
    template:
      textPlaceholder: "{TEXT_HERE}"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          #ssl.trust: smtp-mail.outlook.com
        debug: false
transaction:
  kafka:
    bootstrapServer: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8090
