spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:mariadb://localhost:3306/final_project
    username: root
    password: password
  jpa:
    #show-sql: true
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.ddl-auto: update

connectors:
  login:
    uri: http://login-service
    mock:
      enabled: false
  mail:
    uri: http://mail-service

transaction:
  kafka:
    bootstrapServer: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

server:
  port: 8089