spring:
  application:
    name: wallet-service
  mail:
    host: smtp.gmail.com
    protocol: smtp
    port: 587
    username: group17wa2@gmail.com
    password: Group_17_Wa2_Polito!!
    template:
      textPlaceholder: "{TEXT}"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          #ssl.trust: smtp-mail.outlook.com
        debug: false

connectors:
  users:
    uri: ${USERS_URI:users-service}
    mock:
      enabled: true

transaction:
  kafka:
    bootstrapServer: ${KAFKA_SERVER:transaction-kafka}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
