spring:
  application:
    name: wallet-service

connectors:
  users: users-service

transaction:
  kafka:
    bootstrapServer: transaction-kafka
    topic: transactions

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
